-- MySQL Script generated by MySQL Workbench
-- Вс 08 июл 2018 12:44:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psjudge_frontend_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psjudge_frontend_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psjudge_frontend_test` DEFAULT CHARACTER SET utf8 ;
USE `psjudge_frontend_test` ;

-- -----------------------------------------------------
-- Table `psjudge_frontend`.`contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend_test`.`contest` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend_test`.`contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT(255) NOT NULL,
  `start_time` TIMESTAMP NULL,
  `end_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend_test`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend_test`.`user` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend_test`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active_contest_id` INT NULL,
  `username` TEXT(64) NOT NULL,
  `password` TEXT(32) NOT NULL,
  `roles` SET('admin', 'student', 'judge') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_active_contest_id_idx` (`active_contest_id` ASC),
  CONSTRAINT `fk_active_contest_id`
    FOREIGN KEY (`active_contest_id`)
    REFERENCES `psjudge_frontend_test`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend_test`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend_test`.`assignment` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend_test`.`assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(32) NULL,
  `contest_id` INT NOT NULL,
  `title` TEXT(255) NOT NULL,
  `article` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`, `contest_id`),
  INDEX `fk_contest_id_idx` (`contest_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_contest_id`
    FOREIGN KEY (`contest_id`)
    REFERENCES `psjudge_frontend_test`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend_test`.`solution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend_test`.`solution` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend_test`.`solution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `assignment_id` INT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assignment_id_idx` (`assignment_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `psjudge_frontend_test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignment_id`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `psjudge_frontend_test`.`assignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend_test`.`commit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend_test`.`commit` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend_test`.`commit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solution_id` INT NOT NULL,
  `uuid` VARCHAR(32) NULL,
  `build_status` ENUM('pending', 'failed', 'succeed') NULL DEFAULT 'pending',
  `build_score` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solution_id_idx` (`solution_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_solution_id`
    FOREIGN KEY (`solution_id`)
    REFERENCES `psjudge_frontend_test`.`solution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend_test`.`review` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend_test`.`review` (
  `commit_id` INT NOT NULL AUTO_INCREMENT,
  `reviewer_id` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` TEXT(255) NULL,
  INDEX `fk_commit_id_idx` (`commit_id` ASC),
  INDEX `fk_reviewer_id_idx` (`reviewer_id` ASC),
  UNIQUE INDEX `commit_id_UNIQUE` (`commit_id` ASC),
  CONSTRAINT `fk_commit_id`
    FOREIGN KEY (`commit_id`)
    REFERENCES `psjudge_frontend_test`.`commit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviewer_id`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `psjudge_frontend_test`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
