#!/usr/bin/env bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export GOPATH="${SCRIPT_DIR}/../.."
mkdir -p "${GOPATH}/bin"
(cd "${GOPATH}/bin" && go build ../src/builder_service)
