-- MySQL Script generated by MySQL Workbench
-- Сб 18 авг 2018 21:30:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psjudge_frontend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psjudge_frontend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psjudge_frontend` DEFAULT CHARACTER SET utf8 ;
USE `psjudge_frontend` ;

-- -----------------------------------------------------
-- Table `psjudge_frontend`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`user` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` TEXT(64) NOT NULL,
  `password` TEXT(32) NOT NULL,
  `active_contest_id` INT NULL,
  `roles` SET('admin', 'student', 'judge') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`contest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`contest` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`contest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT(255) NOT NULL,
  `max_reviews` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`assignment` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(32) NULL,
  `contest_id` INT NOT NULL,
  `title` TEXT(255) NOT NULL,
  `article` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`, `contest_id`),
  INDEX `fk_contest_id_idx` (`contest_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_contest_id`
    FOREIGN KEY (`contest_id`)
    REFERENCES `psjudge_frontend`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`solution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`solution` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`solution` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `assignment_id` INT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assignment_id_idx` (`assignment_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `psjudge_frontend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignment_id`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `psjudge_frontend`.`assignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`commit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`commit` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`commit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solution_id` INT NOT NULL,
  `uuid` VARCHAR(32) NULL,
  `build_status` ENUM('pending', 'failed', 'succeed') NULL DEFAULT 'pending',
  `build_score` INT NULL,
  `style_score` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solution_id_idx` (`solution_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_solution_id`
    FOREIGN KEY (`solution_id`)
    REFERENCES `psjudge_frontend`.`solution` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`review` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`review` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commit_id` INT NOT NULL,
  `reviewer_id` INT NOT NULL,
  `score` INT NOT NULL,
  `comment` TEXT(255) NULL,
  INDEX `fk_reviewer_id_idx` (`reviewer_id` ASC),
  UNIQUE INDEX `commit_id_UNIQUE` (`id` ASC),
  INDEX `fk_commit_id_idx` (`commit_id` ASC),
  CONSTRAINT `fk_commit_id`
    FOREIGN KEY (`commit_id`)
    REFERENCES `psjudge_frontend`.`commit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviewer_id`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `psjudge_frontend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`group` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`appointment` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `contest_id` INT NOT NULL,
  `start_time` TIMESTAMP NOT NULL DEFAULT NOW(),
  `end_time` TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_contest_id_idx` (`contest_id` ASC),
  INDEX `fk_group_id_idx` (`group_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_appointment_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `psjudge_frontend`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_contest_id`
    FOREIGN KEY (`contest_id`)
    REFERENCES `psjudge_frontend`.`contest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_frontend`.`group_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_frontend`.`group_relation` ;

CREATE TABLE IF NOT EXISTS `psjudge_frontend`.`group_relation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_id_idx` (`group_id` ASC),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_relation_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `psjudge_frontend`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relation_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `psjudge_frontend`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
