-- MySQL Script generated by MySQL Workbench
-- Чт 05 июл 2018 23:31:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psjudge_builder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psjudge_builder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psjudge_builder` DEFAULT CHARACTER SET utf8 ;
USE `psjudge_builder` ;

-- -----------------------------------------------------
-- Table `psjudge_builder`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_builder`.`assignment` ;

CREATE TABLE IF NOT EXISTS `psjudge_builder`.`assignment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_builder`.`build`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_builder`.`build` ;

CREATE TABLE IF NOT EXISTS `psjudge_builder`.`build` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assignment_id` INT NULL,
  `key` VARCHAR(32) NULL,
  `status` ENUM('pending', 'building', 'failed', 'succeed', 'exception') NULL,
  `language` ENUM('c++', 'pascal') NULL,
  `source` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  INDEX `fk_assignment_id_idx` (`assignment_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_assignment_id`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `psjudge_builder`.`assignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_builder`.`testcase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_builder`.`testcase` ;

CREATE TABLE IF NOT EXISTS `psjudge_builder`.`testcase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assignment_id` INT NULL,
  `key` VARCHAR(32) NULL,
  `input` MEDIUMTEXT NULL,
  `expected` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assignment_id_idx` (`assignment_id` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_testcase_assignment_id`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `psjudge_builder`.`assignment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psjudge_builder`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `psjudge_builder`.`report` ;

CREATE TABLE IF NOT EXISTS `psjudge_builder`.`report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `build_id` INT NOT NULL,
  `tests_passed` INT NOT NULL,
  `tests_total` INT NOT NULL,
  `exception` TINYTEXT NOT NULL,
  `build_log` MEDIUMTEXT NOT NULL,
  `tests_log` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_build_id_idx` (`build_id` ASC),
  CONSTRAINT `fk_build_id`
    FOREIGN KEY (`build_id`)
    REFERENCES `psjudge_builder`.`build` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
